package reglas

import com.Evaluacion.Compra;

rule "Descuento VIP"
    when
        $c: Compra(clienteTipo == "VIP", totalCompra > 500)
    then
        $c.setDescuento(15.0);
        System.out.println("Aplicado 15% a VIP");
end

rule "Descuento NUEVO"
    when
        $c: Compra(clienteTipo == "NUEVO", cantidadProductos > 3)
    then
        $c.setDescuento(10.0);
        System.out.println("Aplicado 10% a NUEVO");
end

rule "Descuento por monto total"
    when
        $c: Compra(totalCompra > 1000)
    then
        $c.setDescuento(20.0);
        System.out.println("Aplicado 20% por monto total");
end
